name: Deploy Remotely
on:
  push:
    branches: [main]

jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 20.x to Build
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build --prod # Build the Angular app for production

      - name: Transfer Build Folder to EC2 Instance
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          SOURCE: "dist/examify-app/"
          TARGET: ${{ secrets.DEPLOY_TARGET }} # The directory on your EC2 instance

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            sudo systemctl restart nginx
